<?php
function getCategories()
{
    $categories = array(
        'category_1' => 'Category 1',
        'category_2' => 'Category 2',
        'category_3' => 'Category 3',
    );
    return $categories;
}

function getTypes()
{
    $types = array(
        'type_1' => 'Type 1',
        'type_2' => 'Type 2',
        'type_3' => 'Type 3',
    );
    return $types;
}

function formatCategories($category)
{
    $categories = array_map(function ($category) {
        return ucfirst(str_replace('_', ' ', $category));
    }, array_keys(unserialize($category)));

    return implode(',', $categories);
}

function rabigorkhali_itonics_products_menu()
{
    $items['admin/itonics/products/add'] = array(
        'title' => 'Itonics Products',
        'description' => 'View Itonics Products.',
        'page callback' => 'rabigorkhali_itonics_products_block_view',
        'access arguments' => array('access rabigorkhali_itonics_products'),
        'weight' => -14,
    );

    $items['admin/itonics/products/%/edit'] = array(
        'title' => 'Itonics Products',
        'description' => 'View Itonics Products.',
        'page callback' => 'rabigorkhali_itonics_products_edit_block_view',
        'page argument' => array(3),
        'access arguments' => array('access rabigorkhali_itonics_products'),
        'weight' => -14,
    );

    $items['admin/itonics/products/%/delete'] = array(
        'title' => 'Itonics Products',
        'description' => 'View Itonics Products.',
        'page callback' => 'rabigorkhali_itonics_products_delete',
        'page argument' => array(3),
        'access arguments' => array('access rabigorkhali_itonics_products'),
        'weight' => -14,
    );

    $items['admin/itonics/products'] = array(
        'title' => 'Itonics Products',
        'description' => 'View Itonics Products.',
        'page callback' => 'rabigorkhali_itonics_products_sort_with_pager_content',
        'access arguments' => array('access rabigorkhali_itonics_products'),
        'weight' => -14,
    );

    $items['admin/itonics/products/%'] = array(
        'title' => 'View Itonics Product',
        'description' => 'View details of an Itonics Product.',
        'page callback' => 'rabigorkhali_itonics_products_view',
        'page arguments' => array(3),
        'access arguments' => array('access rabigorkhali_itonics_products'),
        'weight' => -14,
    );
    return $items;
}


function rabigorkhali_itonics_products_sort_with_pager_content()
{
    $header = array(
        array('data' => t('SN'), 'field' => 'id', 'sort' => 'asc'),
        array('data' => t('Title'), 'field' => 'title'),
        array('data' => t('Category'), 'field' => 'category'),
        array('data' => t('Type'), 'field' => 'type'),
        array('data' => t('Owner Email'), 'field' => 'owner_email'),
        array('data' => t('Expiry Date'), 'field' => 'expiry_date'),
        array('data' => t('Image'), 'field' => 'image'),
        array('data' => t('Action')),
    );

    $query = db_select('rabigorkhali_itonics_products', 'c');
    $query->fields('c', array('id', 'title', 'description', 'summary', 'category', 'type', 'owner_email', 'expiry_date', 'image'));

    $table_sort = $query->extend('TableSort')
        ->orderByHeader($header);
    $pager = $table_sort->extend('PagerDefault')
        ->limit(5);
    $result = $pager->execute();

    $rows = array();
    $incr = 1;
    foreach ($result as $res) {
        $image_output = '';
        if (!empty($res->image)) {
            $file = file_load($res->image);
            $image_output = theme(
                'image_style',
                array(
                    'style_name' => 'thumbnail', // Adjust image style as needed
                    'path' => $file->uri,
                    'alt' => $file->filename,
                    'title' => $file->filename,
                )
            );
        }

        $rows[] = array(
            'data' => array(
                $incr,
                $res->title,
                formatCategories($res->category),
                ucfirst(str_replace('_', ' ', $res->type)),
                $res->owner_email,
                $res->expiry_date,
                $image_output,
                l('View', 'admin/itonics/products/' . $res->id) . ' | ' . l('Edit', 'admin/itonics/products/' . $res->id . '/edit') . ' | ' . l('Delete', 'admin/itonics/products/' . $res->id . '/delete')
            )
        );
        $incr++;
    }

    if (!empty($rows)) {
        $output = theme('table', array('header' => $header, 'rows' => $rows, 'attributes' => array('id' => 'sort-table')));
        $output .= theme('pager');
    } else {
        $output = t("No results found.");
    }

    $output .= l(t('Add new record'), 'admin/itonics/products/add', array('attributes' => array('class' => array('button'))));

    return $output;
}
function rabigorkhali_itonics_products_view($product_id)
{
    $product = rabigorkhali_itonics_products_load($product_id);
    if (!$product) {
        return drupal_not_found();
    }
    $output = array();
    $output[] = array(
        '#type' => 'markup',
        '#markup' => '<p>Title:' . check_plain($product->title) . '</p>',
    );
    $output[] = array(
        '#type' => 'markup',
        '#markup' => '<p>summary:' . check_plain($product->summary) . '</p>',
    );
    $output[] = array(
        '#type' => 'markup',
        '#markup' => '<div>Description:' . unserialize($product->description)['value'] . '</div>',
    );
    $output[] = array(
        '#type' => 'markup',
        '#markup' => '<p>Category: ' . check_plain(formatCategories($product->category)) . '</p>',
    );
    $output[] = array(
        '#type' => 'markup',
        '#markup' => '<p>Type: ' . check_plain(ucfirst(str_replace('_', ' ', $product->type))) . '</p>',
    );
    $output[] = array(
        '#type' => 'markup',
        '#markup' => '<p>Owner Email: ' . check_plain($product->owner_email) . '</p>',
    );
    $output[] = array(
        '#type' => 'markup',
        '#markup' => '<p>Expiry Date: ' . check_plain($product->expiry_date) . '</p>',
    );
    $image_output = '';
    if (!empty($product->image)) {
        $file = file_load($product->image);
        $image_output = theme(
            'image_style',
            array(
                'style_name' => 'thumbnail', // Adjust image style as needed
                'path' => $file->uri,
                'alt' => $file->filename,
                'title' => $file->filename,
            )
        );
    }
    if (!empty($image_output)) {
        $output[] = array(
            '#markup' => $image_output,
        );
    }
    return $output;
}


function rabigorkhali_itonics_products_load($product_id)
{
    $query = db_select('rabigorkhali_itonics_products', 'p')
        ->fields('p')
        ->condition('id', $product_id)
        ->execute();

    return $query->fetchObject();
}

function rabigorkhali_itonics_products_block_view($block_name = "")
{
    if (drupal_is_front_page()) {
        return NULL;
    }
    $form = drupal_get_form('rabigorkhali_itonics_products_form');
    $block = array(
        'content' => $form,
    );
    return $block;
}

function rabigorkhali_itonics_products_form($form, &$form_state)
{
    $form['rabigorkhali_itonics_products_title'] = array(
        '#type' => 'textfield',
        '#title' => t('Title'),
        '#description' => t('The Title of the Itonics Products.'),
        '#size' => 40,
        '#maxlength' => 120,
        '#required' => TRUE,
        '#weight' => 0,
    );
    $form['rabigorkhali_itonics_products_image'] = array(
        '#type' => 'managed_file',
        '#title' => t('Image'),
        '#upload_location' => 'public://rabigorkhali_itonics_products/',
        '#weight' => 1,
    );
    $form['rabigorkhali_itonics_products_summary'] = array(
        '#type' => 'textarea',
        '#rows' => 5,
        '#title' => t('Summary'),
        '#description' => t('A brief summary of the ITONICS Product.'),
        '#weight' => 2,
    );
    $form['rabigorkhali_itonics_products_description'] = array(
        '#type' => 'text_format',
        '#title' => t('Description'),
        '#format' => 'full_html',
        '#required' => TRUE,
        '#description' => t('The detailed description of the ITONICS Product using rich text formatting.'),
        '#weight' => 3,
    );
    $form['rabigorkhali_itonics_products_category'] = array(
        '#type' => 'select',
        '#title' => t('Category'),
        '#options' => getCategories(),
        '#multiple' => TRUE,
        '#required' => TRUE,
        '#description' => t('Select one or more categories for the ITONICS Product.'),
        '#weight' => 4,
        '#attributes' => array(
            'class' => array('rabigorkhali-itonics-products-category-select'), 
        ),
        '#attached' => array(
            'js' => array(
                // drupal_get_path('module', 'rabigorkhali_itonics_products') . '/select2-init.js', 
            ),
        ),
    );
    $form['rabigorkhali_itonics_products_type'] = array(
        '#type' => 'radios',
        '#title' => t('Type'),
        '#options' => getTypes(),
        '#default_value' => 'type_1',
        '#required' => TRUE,
        '#description' => t('Select the type of the ITONICS Product.'),
        '#weight' => 5,
    );
    $form['rabigorkhali_itonics_products_owner_email'] = array(
        '#type' => 'textfield',
        '#title' => t('Owner Email'),
        '#size' => 40,
        '#maxlength' => 255,
        '#required' => TRUE,
        '#description' => t('Enter the email address of the product owner.'),
        '#weight' => 6,
    );
    $form['rabigorkhali_itonics_products_expiry_date'] = array(
        '#type' => 'date_popup',
        '#title' => t('Expiry Date'),
        '#date_format' => 'Y-m-d',
        '#description' => t('Select the expiry date of the ITONICS Product.'),
        '#showCloseButton' => TRUE,
        '#weight' => 7,
        '#title_display' => 'invisible', // This hides the suffix ' Date' from the label.
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Save'),
        '#weight' => 8,
    );
    $form['#submit'][] = 'rabigorkhali_itonics_products_submit_handler';

    return $form;
}

function rabigorkhali_itonics_products_submit_handler($form, &$form_state)
{
    $error = 1;
    if (!isset($form_state['values']['rabigorkhali_itonics_products_title']) || !isset($form_state['values']['rabigorkhali_itonics_products_title'])) {
        $error = 0;
    }

    if ($error) {
        $file = file_save_upload(
            'rabigorkhali_itonics_products_image',
            array(
                'file_validate_is_image' => array(),
                'file_validate_extensions' => array('png gif jpg jpeg'),
            )
        );

        if ($file) {
            $fid = $file->fid;/* FILE UPLOAD SUCCESSFUL */
        } else {
            $fid = 0;
        }
        $rabigorkhali_itonics_products_title = $form_state['values']['rabigorkhali_itonics_products_title'];
        $rabigorkhali_itonics_products_description = serialize($form_state['values']['rabigorkhali_itonics_products_description']); // Extract the value from the text_format element
        $rabigorkhali_itonics_products_summary = $form_state['values']['rabigorkhali_itonics_products_summary'];
        $rabigorkhali_itonics_products_category = $form_state['values']['rabigorkhali_itonics_products_category'];
        $rabigorkhali_itonics_products_type = $form_state['values']['rabigorkhali_itonics_products_type'];
        $rabigorkhali_itonics_products_owner_email = $form_state['values']['rabigorkhali_itonics_products_owner_email'];
        $rabigorkhali_itonics_products_expiry_date = $form_state['values']['rabigorkhali_itonics_products_expiry_date'];
        $nid = db_insert('rabigorkhali_itonics_products')
            ->fields(
                array(
                    'title' => $rabigorkhali_itonics_products_title,
                    'description' => $rabigorkhali_itonics_products_description,
                    'summary' => $rabigorkhali_itonics_products_summary,
                    'category' => serialize($rabigorkhali_itonics_products_category),
                    'type' => $rabigorkhali_itonics_products_type,
                    'owner_email' => $rabigorkhali_itonics_products_owner_email,
                    'expiry_date' => $rabigorkhali_itonics_products_expiry_date,
                    'image' => $fid,
                )
            )
            ->execute();
        drupal_set_message(t('Record has been added!'));
    }
}


function rabigorkhali_itonics_products_delete()
{
    $id = arg(3);
    $num_updated = db_delete('rabigorkhali_itonics_products')
        ->condition('id', $id, '=')
        ->execute();
    drupal_set_message(t('Record has been deleted!'));
    drupal_goto("admin/itonics/products/");
}

function rabigorkhali_itonics_products_edit_block_view($block_name = "")
{
    if (drupal_is_front_page()) {
        return NULL;
    }
    $form = drupal_get_form('rabigorkhali_itonics_products_edit_form');
    $block = array(
        'content' => $form,
    );
    $block['content'][] .= 'Back to Listing';
    return $block;
}

function rabigorkhali_itonics_products_edit_form($form, &$form_state)
{
    $id = arg(3);
    $result = db_query('SELECT * FROM {rabigorkhali_itonics_products} WHERE id = :tid', array(':tid' => $id));
    $record = $result->fetchObject();

    $form['rabigorkhali_itonics_products_title'] = array(
        '#type' => 'textfield',
        '#title' => t('Title'),
        '#default_value' => $record->title,
        '#description' => t('The Title of the Itonics Products.'),
        '#size' => 40,
        '#maxlength' => 120,
        '#required' => TRUE,
        '#weight' => 0,
    );

    $form['rabigorkhali_itonics_products_image'] = array(
        '#type' => 'managed_file',
        '#title' => t('Image'),
        '#description' => t('Upload a new image for the Itonics Product.'),
        '#upload_location' => 'public://rabigorkhali_itonics_products/',
        '#weight' => 1,
    );

    // Display current image if exists
    if (!empty($record->image)) {
        $file = file_load($record->image);
        $image_output = theme(
            'image_style',
            array(
                'style_name' => 'thumbnail', // Adjust image style as needed
                'path' => $file->uri,
                'alt' => $file->filename,
                'title' => $file->filename,
            )
        );
        $form['current_image'] = array(
            '#markup' => $image_output,
            '#prefix' => '<div id="current-image">',
            '#suffix' => '</div>',
            '#weight' => 2,
        );

        $form['delete_image'] = array(
            '#type' => 'checkbox',
            '#title' => t('Delete Current Image'),
            '#default_value' => FALSE,
            '#description' => t('Check this box if you want to delete the current image.'),
            '#weight' => 3,
        );
    }

    $form['rabigorkhali_itonics_products_summary'] = array(
        '#type' => 'textarea',
        '#title' => t('Summary'),
        '#default_value' => $record->summary,
        '#description' => t('A brief summary of the ITONICS Product.'),
        '#rows' => 5,
        '#weight' => 4,
    );

    $form['rabigorkhali_itonics_products_description'] = array(
        '#type' => 'text_format',
        '#title' => t('Description'),
        '#format' => unserialize($record->description)['format'],
        '#rows' => 10,
        '#columns' => 40,
        '#default_value' => unserialize($record->description)['value'],
        '#required' => TRUE,
        '#description' => t('The detailed description of the ITONICS Product using rich text formatting.'),
        '#weight' => 5,
    );

    $form['rabigorkhali_itonics_products_category'] = array(
        '#type' => 'select',
        '#title' => t('Category'),
        '#default_value' => $record->category ? unserialize($record->category) : array(),
        '#options' => getCategories(),
        '#multiple' => TRUE,
        '#required' => TRUE,
        '#description' => t('Select one or more categories for the ITONICS Product.'),
        '#weight' => 6,
    );

    $form['rabigorkhali_itonics_products_type'] = array(
        '#type' => 'radios',
        '#title' => t('Type'),
        '#default_value' => $record->type,
        '#options' => getTypes(),
        '#required' => TRUE,
        '#description' => t('Select the type of the ITONICS Product.'),
        '#weight' => 7,
    );

    $form['rabigorkhali_itonics_products_owner_email'] = array(
        '#type' => 'textfield',
        '#title' => t('Owner Email'),
        '#default_value' => $record->owner_email,
        '#size' => 40,
        '#maxlength' => 255,
        '#required' => TRUE,
        '#description' => t('Enter the email address of the product owner.'),
        '#weight' => 8,
    );

    $form['rabigorkhali_itonics_products_expiry_date'] = array(
        '#type' => 'date_popup',
        '#date_format' => 'Y-m-d',
        '#title' => t('Expiry Date'),
        '#default_value' => $record->expiry_date ?? date('Y-m-d'),
        '#required' => TRUE,
        '#description' => t('Select the expiry date of the ITONICS Product.'),
        '#weight' => 9,
        '#title_display' => 'invisible', // This hides the suffix ' Date' from the label.
    );

    // Hidden ID field
    $form['id'] = array(
        '#type' => 'hidden',
        '#value' => $id,
        '#weight' => 10,
    );

    // Submit button
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Save'),
        '#weight' => 11,
    );

    // Submit handler
    $form['#submit'][] = 'rabigorkhali_itonics_products_edit_submit_handler';

    return $form;
}

function rabigorkhali_itonics_products_edit_submit_handler($form, &$form_state)
{
    $error = FALSE;
    if (
        !isset($form_state['values']['rabigorkhali_itonics_products_title']) || empty($form_state['values']['rabigorkhali_itonics_products_title']) ||
        !isset($form_state['values']['rabigorkhali_itonics_products_description']) || empty($form_state['values']['rabigorkhali_itonics_products_description']) ||
        !isset($form_state['values']['rabigorkhali_itonics_products_summary']) || empty($form_state['values']['rabigorkhali_itonics_products_summary']) ||
        !isset($form_state['values']['rabigorkhali_itonics_products_category']) || empty($form_state['values']['rabigorkhali_itonics_products_category']) ||
        !isset($form_state['values']['rabigorkhali_itonics_products_type']) || empty($form_state['values']['rabigorkhali_itonics_products_type']) ||
        !isset($form_state['values']['rabigorkhali_itonics_products_owner_email']) || empty($form_state['values']['rabigorkhali_itonics_products_owner_email'])
    ) {
        $error = TRUE;
    }
    if (!$error) {
        $id = $form_state['values']['id'];
        $rabigorkhali_itonics_products_title = $form_state['values']['rabigorkhali_itonics_products_title'];
        $rabigorkhali_itonics_products_description = serialize($form_state['values']['rabigorkhali_itonics_products_description']);
        $rabigorkhali_itonics_products_summary = $form_state['values']['rabigorkhali_itonics_products_summary'];
        $rabigorkhali_itonics_products_category = $form_state['values']['rabigorkhali_itonics_products_category'];
        $rabigorkhali_itonics_products_type = $form_state['values']['rabigorkhali_itonics_products_type'];
        $rabigorkhali_itonics_products_owner_email = $form_state['values']['rabigorkhali_itonics_products_owner_email'];
        $rabigorkhali_itonics_products_expiry_date = $form_state['values']['rabigorkhali_itonics_products_expiry_date'];

        $data = array(
            'title' => $rabigorkhali_itonics_products_title,
            'description' => $rabigorkhali_itonics_products_description,
            'summary' => $rabigorkhali_itonics_products_summary,
            'category' => serialize($rabigorkhali_itonics_products_category), // Serialize for multiple values
            'type' => $rabigorkhali_itonics_products_type,
            'owner_email' => $rabigorkhali_itonics_products_owner_email,
            'expiry_date' => $rabigorkhali_itonics_products_expiry_date,
        );

        // Handle image update if file is uploaded
        if (!empty($form['rabigorkhali_itonics_products_image'])) {
            $file = file_save_upload(
                'rabigorkhali_itonics_products_image',
                array(
                    'file_validate_is_image' => array(), // Ensure it's an image file
                    'file_validate_extensions' => array('png gif jpg jpeg'), // Allowed file types
                )
            );

            if ($file) {
                // Save the file
                if ($file = file_move($file, 'public://products/')) {
                    $data['image'] = $file->fid;

                    // Delete old image if checkbox is checked
                    if (!empty($form_state['values']['delete_image'])) {
                        file_delete(file_load($record->image));
                        $data['image'] = NULL; // Reset image field in database
                    }
                }
            }
        }
        if (!empty($form_state['values']['rabigorkhali_itonics_products_image'])) {
            $file = file_save_upload(
                'rabigorkhali_itonics_products_image',
                array(
                    'file_validate_is_image' => array(), // Ensure it's an image file
                    'file_validate_extensions' => array('png gif jpg jpeg'), // Allowed file types
                )
            );

            if ($file) {
                // Save the file
                if ($file = file_move($file, 'public://products/')) {
                    $data['image'] = $file->fid;

                    // Delete old image if checkbox is checked
                    if (!empty($form_state['values']['delete_image'])) {
                        // Load the record again to get the current image fid
                        $result = db_query('SELECT image FROM {rabigorkhali_itonics_products} WHERE id = :id', array(':id' => $id));
                        $record = $result->fetchObject();
                        if ($record && isset($record->image)) {
                            file_delete(file_load($record->image));
                            $data['image'] = NULL; // Reset image field in database
                        }
                    }
                }
            }
        } elseif (!empty($form_state['values']['delete_image'])) {
            // Delete old image if only checkbox is checked without new upload
            // Load the record again to get the current image fid
            $result = db_query('SELECT image FROM {rabigorkhali_itonics_products} WHERE id = :id', array(':id' => $id));
            $record = $result->fetchObject();
            if ($record && isset($record->image)) {
                file_delete(file_load($record->image));
                $data['image'] = NULL; // Reset image field in database
            }
        }
        $num_updated = db_update('rabigorkhali_itonics_products')
            ->fields($data)
            ->condition('id', $id)
            ->execute();

        drupal_set_message(t('Record has been updated!'));
    } else {
        drupal_set_message(t('Error: Please fill in all required fields.'), 'error');
    }
}

function rabigorkhali_itonics_products_permission()
{
    return array(
        'access rabigorkhali_itonics_products' => array(
            'title' => t('View Itonics Products'),
            'description' => t(
                'Customizing the Itonics Products requires the !permission-name permission.',
                array(
                    '!permission-name' => l(t('Administer blocks'), 'admin/people/permissions', array('fragment' => 'module-block')),
                )
            ),
        ),
    );
}

function rabigorkhali_itonics_products_init()
{
    // drupal_add_js('https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js', array('type' => 'external'));

    // Include Select2 CSS from CDN
    // drupal_add_css('https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css', array('type' => 'external'));

    // // Include Select2 JS from CDN
    // drupal_add_js('https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js', array('type' => 'external'));

    // drupal_add_js('https://code.jquery.com/jquery-3.6.0.min.js', array('type' => 'external'));
    // drupal_add_js(drupal_get_path('module', 'rabigorkhali_itonics_products') . '/js/select2.min.js');
    // drupal_add_css(drupal_get_path('module', 'rabigorkhali_itonics_products') . '/css/select2.min.css');
}
